name: Build and Package DevStudio CRM

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
    - name: 1. Tải code về máy ảo
      uses: actions/checkout@v4

    - name: 2. Kiểm tra danh sách file (Để debug)
      run: dir

    - name: 3. Cài đặt Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 4. Biên dịch Code
      run: |
        mkdir bin
        javac -d bin QuanLyKhachHang.java

    - name: 5. Đóng gói JAR
      run: |
        jar cfe code-wed.jar QuanLyKhachHang -C bin .

    - name: 6. Cài đặt Launch4j
      run: |
        curl -L -o launch4j.zip https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-win32.zip/download
        tar -xf launch4j.zip

    - name: 7. Đúc file EXE
      run: |
        .\launch4j\launch4jc.exe software-quanly.xml

    - name: 8. Tạo file firebase.json từ Secret
      env:
        FIREBASE_SECRET: ${{ secrets.FIREBASE_JSON_CONTENT }}
      run: |
        $env:FIREBASE_SECRET | Out-File -FilePath firebase.json -Encoding utf8

    - name: 9. Nén và Giao hàng
      run: |
        mkdir Release
        copy DevStudio_CRM.exe Release\
        copy firebase.json Release\
        Compress-Archive -Path Release\* -DestinationPath DevStudio_CRM_Final.zip

    - name: 10. Upload sản phẩm
      uses: actions/upload-artifact@v4
      with:
        name: Windows-App-Release
        path: DevStudio_CRM_Final.zip